name: Android Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK
        run: |
          yes | sdkmanager --licenses
          sdkmanager \
            "platforms;android-34" \
            "build-tools;35.0.0"

      - name: Build AAR
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Upload AAR
        uses: actions/upload-artifact@v4
        with:
          name: aar
          path: "**/*.aar"
          
